export const crapienv: {
  IDENTITY_SERVICE: string;
  WORKSHOP_SERVICE: string;
  CHATBOT_SERVICE: string;
  COMMUNITY_SERVICE: string;
  TRACEABLE_CAPTCHA_SITE_KEY: string;
  TRACEABLE_CAPTCHA_URL: string;
  TRACEABLE_CAPTCHA_MODE: string;
  TRACEABLE_CAPTCHA_TOKEN_CALLBACK_ENABLED: boolean;
} = {
  IDENTITY_SERVICE: "identity/",
  WORKSHOP_SERVICE: "workshop/",
  CHATBOT_SERVICE: "chatbot/",
  COMMUNITY_SERVICE: "community/",
  TRACEABLE_CAPTCHA_SITE_KEY: "T-8784729",
  TRACEABLE_CAPTCHA_URL: "https://captcha.traceable.ai",
  TRACEABLE_CAPTCHA_MODE: "EXTERNAL",
  TRACEABLE_CAPTCHA_TOKEN_CALLBACK_ENABLED: true
};
